### ISSUE TITLE
Replace CONSTRUCT .. WHEN with CONSTRUCT … WHERE 

### ISSUE THREAD

**Issue by peterboncz** [ldbc/gcore-spark#2]
- in parser (very simple renaming)

**Comment by ramhgarcias** [comment]
Branch issue2 commit: 800b43e487b0225ff4b5b4c8ecb54bbd304c9283

**Comment by ramhgarcias** [comment]
fixed by https://github.com/ldbc/gcore-spark/commit/3ff80fed77026da917fd9736c2c54f0effb6ca1c
