### ISSUE TITLE
CREATE and DROP GRAPH

### ISSUE THREAD

**Issue by peterboncz** [ldbc/gcore-spark#6]
Support CREATE GRAPH x, which indicates that graph x is persistent, and that the catalog has to be changed also in a persistent way. 

Also support DROP GRAPH x, which indicates that a graph x that is persistent has to be deleted from Spark and the catalog.

CREATE GRAPH x should have a default semantics (for example, it should be default rule that indicates where graph x should be stored and in which format). 

CREATE GRAPH x should also give the possibility to the user to specify some parameters such as directory where x is going to be stored, format for x, …

It could be something like CREATE GRAPH x (directory="/foo", format="parquet") <construct query>

**Comment by ramhgarcias** [comment]
Fixed by
2f1d54efa9312a9363f5396c25a1505b2d5341a6
364f0de60917b0d67cbdf3ed132c0fccb0893cf5
