### ISSUE TITLE
GRAPH VIEW x AS CONSTRUCT ... 

### ISSUE THREAD

**Issue by peterboncz** [ldbc/gcore-spark#7]
- This is lightweight version of CREATE GRAPH
- Keep the result dataframes of the CONSTRUCT query around in the Spark session(now they get de-allocated), but do not save them persistently as in CREATE GRAPH
- Temporarily add the meta-data of the CONSTRUCT query to the catalog under graph name X (the new catalog should not be stored in disk)

**Comment by ramhgarcias** [comment]
Fixed by https://github.com/ldbc/gcore-spark/commit/07c0c1c20ab270e8e301d476a59939c976257f9f
